apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-couchdb-0
  labels:
    app: couchdb
    project: valuphone
    environment: production
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-couchdb-1
  labels:
    app: couchdb
    project: valuphone
    environment: production
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-couchdb-2
  labels:
    app: couchdb
    project: valuphone
    environment: production
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
